trigger:
  - infrastructure


variables:
- template: deploy/pipeline-stages/vars.yml

stages:
- template: deploy/pipeline-stages/infrastructure_deploy.yml
- template: deploy/pipeline-stages/build.yml
- template: deploy/pipeline-stages/deploy.yml