# Trigger builds on commits to branches
trigger:
  - test_pipeline

# Do not trigger builds on PRs
pr: none

variables:
- group: Infrastructure
- name: buildConfiguration 
  value: Release
- name: registryUser
  value: diplomaContainerRegistry
- name: regisrtyUrl
  value: diplomacontainerregistry.azurecr.io

extends:
  template: pipeline-shared.yml
  template: test.yml