trigger:
  - test_pipeline


variables:
- group: Infrastructure
- name: buildConfiguration 
  value: Release
- name: registryUser
  value: diplomaContainerRegistry
- name: regisrtyUrl
  value: diplomacontainerregistry.azurecr.io


stages:
- template: pipeline-shared.yml
- template: test.yml