trigger:
  - release

variables:
- template: deploy/pipeline-stages/vars.yml

stages:
- template: deploy/pipeline-stages/quality-gates.yml
- template: deploy/pipeline-stages/build.yml
- template: deploy/pipeline-stages/deploy.yml