trigger:
  - test_pipeline


variables:
- template: deploy/pipeline-stages/vars.yml


stages:
- ${{ if eq(variables['build.SourceBranchName'], 'test_pipline') }}:
- template: deploy/pipeline-stages/infrastructure.yml
- template: deploy/pipeline-stages/quality-gates.yml
- template: deploy/pipeline-stages/build.yml
- template: deploy/pipeline-stages/deploy.yml