version: '3.8'

services:
  nhl_app:
    build: ./
    command: /app/main
    ports:
      - 80:80
    environment:
      - DB_HOST=db
      - DB_LOGIN=nhl
      - DB_DB_NAME=nhl 
      - DB_PASS=s3cr3t
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=nhl
      - POSTGRES_USER=nhl
      - POSTGRES_PASSWORD=s3cr3t    
    ports:
      - 5432:5432