version: '3.8'

services:
  nhl_app:
    build: ./
    command: /app/main
    ports:
      - 80:80
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=nhl
      - POSTGRES_PASSWORD=s3cr3t      
    ports:
      - 5432:5432
