apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-configmap
  labels:
    app: {{ .Values.name }}
    heritage: {{ .Release.Service }}
data:
  DB_HOST: {{ .Values.db_config.host }}
  DB_LOGIN: {{ .Values.db_config.login }}
  DB_NAME: {{ .Values.db_config.name }}