apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
      heritage: {{ .Release.Service }}
  replicas: {{.Values.replicas }}
  template:
    metadata:
      name: {{.Values.name}}
      labels:
        app: {{.Values.name}}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: {{.Values.name}}
          image: {{.Values.image.repository}}:latest
          imagePullPolicy: {{.Values.image.imagePullPolicy}}
          ports:
            - containerPort: {{.Values.port}}
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
        - name: {{.Values.image.imagePullSecret}}
  selector:
    matchLabels:
      app: {{.Values.name}}
      heritage: {{ .Release.Service }}
