apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-secret
type: Opaque
data:
  ##DB_HOST: ZGlwbG9tYS1wc3Fsc2VydmVyLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  DB_HOST: ZGlwbG9tYS10ZXN0LXBzcWxzZXJ2ZXIucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29t #diploma-test-psqlserver.postgres.database.azure.com
  DB_LOGIN: cHNxbGFkbWludW5AZGlwbG9tYS1wc3Fsc2VydmVy #psqladminun@diploma-psqlserver
  DB_PASS: {{ .Values.db_pass }} 
  ##DB_PASS: SEBTaDFDb1IzIUA= #H@Sh1CoR3!@

  #Unable to connection to database: failed to connect to `host=diploma-test-psqlserver.postgres.database.azure.com user=psqladminun@diploma-psqlserver database=nhl`: hostname resolving error (lookup diploma-test-psqlserver.postgres.database.azure.com on 10.0.0.10:53: no such host)