apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-secret
type: Opaque
data:
  DB_HOST: ZGlwbG9tYS1wc3Fsc2VydmVyLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  DB_LOGIN: cHNxbGFkbWluQGRpcGxvbWEtcHNxbHNlcnZlcg==
  DB_PASS: .Values.db_pass