apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-secret
type: Opaque
data:
  #DB_HOST: ZGlwbG9tYS1wc3Fsc2VydmVyLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  DB_HOST: ZGlwbG9tYS10ZXN0LXBzcWxzZXJ2ZXIucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29t
  DB_LOGIN: cHNxbGFkbWludW5AZGlwbG9tYS1wc3Fsc2VydmVy
  #DB_PASS: {{ .Values.db_pass }} 
  DB_PASS: SEBTaDFDb1IzIUA=