apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  ports:
    - name: {{ .Values.name }}
      port: {{ .Values.port }}
  selector:
    app: {{ .Values.name }}
    release: {{ .Release.Name }}

