name: nhl
namespace: production
replicas: 1

port: 80

db_config:
  host: diploma-psqlserver.postgres.database.azure.com
  login: psqladminun@diploma-psqlserver
  name: nhl_prod

image:
  repository: diplomacontainerregistry.azurecr.io
  imageName: nhl
  tag: latest
  pullPolicy: Always
  imagePullSecret: artifactory

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi