name: nhl
namespace: develop
replicas: 1

port: 80

image:
  repository: diplomacontainerregistry.azurecr.io/diplomacontainerregistry.azurecr.io/nhl
  tag: latest
  pullPolicy: Always
  imagePullSecret: artifactory

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

db_pass: password