name: nhl-dev
namespace: develop
replicas: 1

port: 80

db_config:
  host: diploma-psqlserver.postgres.database.azure.com
  login: psqladminun@diploma-psqlserver
  name: nhl_dev

image:
  repository: diplomacontainerregistry.azurecr.io
  imageName: nhl
  tag: latest
  pullPolicy: Always
  imagePullSecret: artifactory

resources:
  requests:
    cpu: 50m
    memory: 170Mi

ingress:
  enabled: true
  name: nhl-dev-ingress
  annotations:
    enable-vts-status: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Server: ";
    nginx.ingress.kubernetes.io/proxy-body-size: 15m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/ssl-ciphers: ALL:!aNULL:!EXPORT56:RC4+RSA:+HIGH
    nginx.org/proxy-hide-headers: Server, X-Powered-By, X-AspNet-Version, X-AspNet-Mvc-Version
    nginx.org/server-tokens: "False"
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"   
  hosts:
    - host: nhl-dev.hgest.ru
      paths:
        path: "/"
  #tls:
  #  - hosts:
  #      - nhl-dev.hgest.ru
  #    secretName: tls-secret