stages:
- stage: 'infrastucture'
  displayName: 'Destroy Infrastucture'
  condition: succeeded()
  jobs:
  - job: Destroy
    displayName: 'Destroy Azure Infrastructure'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - script: |
        # Cd to terraform folder.
        cd deploy/terraform/infrastructure
   
        # Exit when any command returns a failure status.
        set -e
        # Write terraform.tfvars.
        echo 'resource_group_location = "'$(ResourceGroupLocation)'"' | tee terraform.tfvars
        # Write backend.tfvars.
        echo 'resource_group_name = "tf-storage-rg"' | tee backend.tfvars
        echo 'storage_account_name = "'$(StorageAccountName)'"' | tee -a backend.tfvars
        echo 'container_name = "tfstate"' | tee -a backend.tfvars
        echo 'key = "terraform.tfstate"' | tee -a backend.tfvars
        # Initialize Terraform.
        terraform init -input=false -backend-config="backend.tfvars"

        # Destroy the Terraform plan.
        terraform destroy -input=false -auto-approve

      name: 'RunTerraform'
      displayName: 'Run Terraform'
      env:
        TF_VAR_arm_client_id: $(ARM_CLIENT_ID)
        TF_VAR_arm_client_secret: $(ARM_CLIENT_SECRET)
        TF_VAR_db_pass: $(DB_PASS)
        TF_VAR_registry_user: $(registryUser)
        TF_VAR_registry_url: $(registryUrl)