stages:
- stage: 'SonarQube'
  displayName: 'SonarQube'
  condition: succeeded()
  jobs:
  - job: Test_Code
    displayName: 'Test Code'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - script: |
        #Prepare sonar-scanner
        mkdir /downloads/sonarqube -p
        cd /downloads/sonarqube
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
        unzip sonar-scanner-cli-4.2.0.1873-linux.zip
        mv sonar-scanner-4.2.0.1873-linux /opt/sonar-scanner
        cat /opt/sonar-scanner/conf/sonar-scanner.properties
        export PATH="$PATH:/opt/sonar-scanner/bin"
        echo "START CODE SCAN"
      
        #Test code
        sonar-scanner \
          -Dsonar.projectKey=Diploma-go \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://20.50.49.188:9000 \
          -Dsonar.login=0cac1b53bd68e2d758d0ddb429e84b539d70c210 \
          -Dsonar.qualitygate.wait=true

      name: 'Quality_Gates'
      displayName: 'Quality Gates'