stages:
- stage: 'Quality_Gates'
  displayName: 'Quality Gates'
  condition: succeeded()
  jobs:
  - job: Test_Code
    displayName: 'Test Code'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - script: |
        #Prepare sonar-scanner
        mkdir /downloads/sonarqube -p
        cd /downloads/sonarqube
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
        unzip sonar-scanner-cli-4.2.0.1873-linux.zip
        mv sonar-scanner-4.2.0.1873-linux /opt/sonar-scanner
        cat /opt/sonar-scanner/conf/sonar-scanner.properties
        export PATH="$PATH:/opt/sonar-scanner/bin"
        echo "START CODE SCAN"
      
        #Test code
        sonar-scanner \
          -Dsonar.projectKey=Diploma-go \
          -Dsonar.sources=. \
          -Dsonar.host.url=$sonar_host \
          -Dsonar.login=$sonar_project_id \
          -Dsonar.qualitygate.wait=true

      name: 'SonarQube'
      displayName: 'Sonar_Qube'
      env:
        sonar_host: $(SONAR_HOST)
        sonar_project_id: $(SONAR_PROJECT_ID)  